export default {
	LOADING: 'LOADING',
	SHOWINTRO: 'SHOWINTRO',
	LANGUAGECODE: 'LANGUAGECODE',
	SHOWMODAL: 'SHOWMODAL',
	RESETSTATE: 'RESETSTATE',

	SIGNUP : 'SIGNUP',
	SIGNIN : 'SIGNIN',
	LOGOUT : 'LOGOUT',
	FORGOTPASSWORD : 'FORGOTPASSWORD',

};