export default {
	LOADING: 'LOADING',
	SETCURRENTROUTE: 'SETCURRENTROUTE',

	SIGNUP : 'SIGNUP',
	SIGNIN : 'SIGNIN',
	LOGOUT : 'LOGOUT',
	CURRENT_USER : 'CURRENT_USER',
	USER_AVAILIBILITY_CHANGED : 'USER_AVAILIBILITY_CHANGED',
	CHANGE_PROFILE : 'CHANGE_PROFILE',
};